name: Generate themes.json
on: [workflow_dispatch]

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash tools/generate.sh
          git config user.name  github-actions[bot]
          git config user.email github-actions[bot]@github.com
          git add .
          git commit -m "------- Generate themes.json -------"
          git push


